# Generated by Django 4.2.1 on 2023-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ovqat nomi')),
                ('rasm', models.ImageField(upload_to='images', verbose_name='Ovqat rasmi')),
                ('retsept', models.TextField(verbose_name='Ovqat retsepti')),
                ('narxi', models.IntegerField(default=0, null='True', verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menular',
            },
        ),
    ]
