# Generated by Django 4.2 on 2023-08-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_obed_ujin_alter_menu_retsept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obed',
            options={'verbose_name': 'obed', 'verbose_name_plural': 'obedlar'},
        ),
        migrations.AlterModelOptions(
            name='ujin',
            options={'verbose_name': 'ujin', 'verbose_name_plural': 'ujinlar'},
        ),
    ]
