# Generated by Django 4.2 on 2023-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_obed_options_alter_ujin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Povar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Povar nomi')),
                ('rasm', models.ImageField(upload_to='images', verbose_name='Povar rasmi')),
                ('facebook', models.URLField(default='#', null=True, verbose_name='facebook silka')),
                ('telegram', models.URLField(default='#', null=True, verbose_name='telegram silka')),
                ('instagram', models.URLField(default='#', null=True, verbose_name='instagram silka')),
                ('twitter', models.URLField(default='#', null=True, verbose_name='x silka')),
            ],
            options={
                'verbose_name': 'povar',
                'verbose_name_plural': 'povarlar',
            },
        ),
    ]
