# Generated by Django 4.2 on 2023-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_povar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povar',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='povar',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/', null=True, verbose_name='facebook silka'),
        ),
        migrations.AlterField(
            model_name='povar',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/', null=True, verbose_name='instagram silka'),
        ),
        migrations.AlterField(
            model_name='povar',
            name='telegram',
            field=models.URLField(default='https://www.telegram.com/', null=True, verbose_name='telegram silka'),
        ),
    ]
