# Generated by Django 4.2 on 2023-08-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_povar_haqida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povar',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Povar ismi'),
        ),
    ]
