# Generated by Django 4.2 on 2023-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_povar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povar',
            name='name',
            field=models.CharField(default='Paloncha Pistonchiyev', max_length=255, verbose_name='Povar ismi'),
        ),
    ]
